<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MBobot extends CI_Model
{

    public $table = 'bobot';
    public $id = 'id_bobot';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // function get_by_id_subkriteria($id)
    // {
    //     $this->db->where("nama_subkriteria",$id);
    //     //$this->db->get($this->table)->result();
    //     //echo $this->db->last_query();
    //     //exit;
    //     return $this->db->get($this->table)->result();
    // }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_bobot', $q);
	$this->db->or_like('id_kriteria', $q);
	$this->db->or_like('id_subkriteria', $q);
	$this->db->or_like('nilai_bobot', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->select('t.*,k.nama_kriteria, s.nama_subkriteria');
    $this->db->from('bobot t');
    $this->db->join('kriteria k', 'k.id_kriteria = t.id_kriteria');
    $this->db->join('sub_kriteria s', 's.id_subkriteria = t.id_subkriteria');
    
        $this->db->order_by('t.id_bobot', $this->order);
        $this->db->like('t.id_bobot', $q);
	$this->db->or_like('t.id_kriteria', $q);
	$this->db->or_like('t.id_subkriteria', $q);
	$this->db->or_like('t.nilai_bobot', $q);
	$this->db->or_like('t.keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MBobot.php */
/* Location: ./application/models/MBobot.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-12 06:14:01 */
/* http://harviacode.com */