<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MUser extends CI_Model
{

    public $table = 'user1';
    public $id = 'id_user1';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    //Cek user
    public function CheckUser($username, $password)
    {
        $query = $this->db->get_where($this->table,
                array('username'=>$username,
                      'password'=>$password)
                );
        //cek apakah ada atau tidak
         if ($query->num_rows() > 0){
             return true;
         } else {
             return false;
         }
    }

     //cek username
     function get_by_username($username)
     {
          $this->db->where('username', $username);
          return $this->db->get($this->table)->row();
     } 


    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_user1', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('hak_akses', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_user1', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('hak_akses', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MUser.php */
/* Location: ./application/models/MUser.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-05-19 05:44:54 */
/* http://harviacode.com */